# Generated by Django 5.1 on 2025-09-10 15:43

import dashboard.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stadium', models.CharField(blank=True, max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('season', models.ForeignKey(default=dashboard.models.get_current_season, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='dashboard.season')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('home_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('finished', 'Finished')], default='upcoming', max_length=20)),
                ('match_type', models.CharField(choices=[('division_two', 'Division Two League'), ('sub_middle', 'Sub Middle League'), ('middle', 'Middle League'), ('fa_cup', 'FA Cup'), ('friendlies', 'Club Friendlies')], default='division_two', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(default=dashboard.models.get_current_season, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='dashboard.season')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='matches.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='matches.team')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.PositiveIntegerField(default=0)),
                ('won', models.PositiveIntegerField(default=0)),
                ('drawn', models.PositiveIntegerField(default=0)),
                ('lost', models.PositiveIntegerField(default=0)),
                ('goal_for', models.PositiveIntegerField(default=0)),
                ('goal_against', models.PositiveIntegerField(default=0)),
                ('goal_difference', models.IntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('match_type', models.CharField(choices=[('division_two', 'Division Two League'), ('sub_middle', 'Sub Middle League'), ('middle', 'Middle League'), ('fa_cup', 'FA Cup'), ('friendlies', 'Club Friendlies')], default='division_two', max_length=50)),
                ('season', models.ForeignKey(default=dashboard.models.get_current_season, on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='dashboard.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.team')),
            ],
            options={
                'unique_together': {('team', 'match_type', 'season')},
            },
        ),
    ]
