# Generated by Django 5.1 on 2025-09-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubteammember',
            name='name',
        ),
        migrations.AddField(
            model_name='clubteammember',
            name='first_name',
            field=models.CharField(default='Blakk', max_length=50),
        ),
        migrations.AddField(
            model_name='clubteammember',
            name='last_name',
            field=models.CharField(default='Senses', max_length=50),
        ),
    ]
