# Generated by Django 5.1 on 2025-09-10 15:43

import dashboard.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='player_photos/')),
                ('joined_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jersey_number', models.PositiveIntegerField()),
                ('appearances', models.PositiveIntegerField(default=0)),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('clean_sheets', models.PositiveIntegerField(default=0)),
                ('big_chances_created', models.PositiveIntegerField(default=0)),
                ('tackles_won', models.PositiveIntegerField(default=0)),
                ('clearances', models.PositiveIntegerField(default=0)),
                ('penalties_taken', models.PositiveIntegerField(default=0)),
                ('penalties_scored', models.PositiveIntegerField(default=0)),
                ('yellow_cards', models.PositiveIntegerField(default=0)),
                ('red_cards', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('season', models.ForeignKey(default=dashboard.models.get_current_season, on_delete=django.db.models.deletion.CASCADE, related_name='player_seasons', to='dashboard.season')),
                ('positions', models.ManyToManyField(blank=True, to='players.position')),
            ],
            options={
                'unique_together': {('player', 'season')},
            },
        ),
        migrations.AddField(
            model_name='player',
            name='seasons',
            field=models.ManyToManyField(through='players.PlayerSeason', to='dashboard.season'),
        ),
    ]
