# Generated by Django 5.1 on 2025-09-10 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(default='Blakk', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='Senses', max_length=50),
        ),
        migrations.CreateModel(
            name='PlayerMatchPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_played', models.PositiveIntegerField(default=0)),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('clean_sheet', models.BooleanField(default=False)),
                ('big_chances_created', models.PositiveIntegerField(default=0)),
                ('tackles_won', models.PositiveIntegerField(default=0)),
                ('clearances', models.PositiveIntegerField(default=0)),
                ('penalties_taken', models.PositiveIntegerField(default=0)),
                ('penalties_scored', models.PositiveIntegerField(default=0)),
                ('yellow_cards', models.PositiveIntegerField(default=0)),
                ('red_cards', models.PositiveIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_performances', to='matches.match')),
                ('player_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='players.playerseason')),
            ],
            options={
                'unique_together': {('player_season', 'match')},
            },
        ),
    ]
