# Generated by Django 5.1 on 2025-09-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_remove_player_name_player_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='playermatchperformance',
            name='penalties_saved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playermatchperformance',
            name='saves',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerseason',
            name='penalties_saved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerseason',
            name='saves',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
