# Generated by Django 5.1 on 2025-09-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_slug_playermatchperformance_penalties_saved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerseason',
            name='penalties_taken',
        ),
        migrations.AddField(
            model_name='playermatchperformance',
            name='match_type',
            field=models.CharField(choices=[('division_two', 'Division Two League'), ('sub_middle', 'Sub Middle League'), ('middle', 'Middle League'), ('fa_cup', 'FA Cup'), ('friendlies', 'Club Friendlies')], default='division_two', max_length=20),
        ),
        migrations.AddField(
            model_name='playerseason',
            name='debut_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerseason',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='playerseason',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
