# Generated by Django 5.1 on 2025-09-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_remove_playerseason_penalties_taken_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerseason',
            name='debut_date',
        ),
        migrations.RemoveField(
            model_name='playerseason',
            name='height',
        ),
        migrations.RemoveField(
            model_name='playerseason',
            name='place_of_birth',
        ),
        migrations.AddField(
            model_name='player',
            name='debut_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
